### ISSUE TITLE
Multiply by 100?

### ISSUE THREAD

**Issue by jskeet** [novalagung/skeetoverflow#1]
Currently (according to the README) this will show Gordon Linoff as having 0.899665% of my reputation - it should actually be 89.9665%. (Just as an example.) Basically I think it's currently showing the raw proportion but labelling it as a percentage.

**Comment by novalagung** [comment]
wow, it's an honor to be responded to by you

my initial idea was to your rep as the max number, which is `1` not `100`. I guess it's kind of invalid since I use percentage here.
I'll update the code to multiply the number by 100
